### ISSUE TITLE
findClosestEnergyPickup

### ISSUE THREAD

**Issue by 89gsc** [kaaku/screeps#1]
This should also look for dropped energy as its very ineffective at building containers where miners are because the build wont take the energy the miner dropped it will go to the nearest energy container instead which in some cases means it travels the length of the room to get energy.

**Comment by gsc89** [comment]
I did this as a quick edit but it would be better to compare which is closest
```

  var droppedEnergy = builder.room.find(FIND_DROPPED_ENERGY, {
                filter: energy => {
                return energy;
        }
        });

        var storagesAndContainers = _.filter(structures, s => {
            return s.structureType === STRUCTURE_STORAGE || s.structureType === STRUCTURE_CONTAINER;
        });

        if (!_.isEmpty(droppedEnergy)) {
            pickup = builder.pos.findClosestByRange(droppedEnergy);
        } else if (!_.isEmpty(storagesAndContainers)) {
            pickup = builder.pos.findClosestByRange(storagesAndContainers);
        } else {
            pickup = builder.pos.findClosestByRange(structures);
        }

```

**Comment by kaaku** [comment]
Thanks for the input! I decided to resolve this so that the builders pickup nearby energy piles, but don't go out of their way to get them. The carriers already have logic for fetching distant energy piles, IF the piles have enough energy to be worth it.

**Comment by 89gsc** [comment]
Your welcome, I have been trying many different screeps AI's I find to get ideas. Yours is one of the more stable of them and has some nice unique quirks like the priority and assignee system you have made. 

Can see this becoming a great AI if you continue down this vein of coding style.
